### ISSUE TITLE
How can I compile this project on 10.10?

### ISSUE THREAD

**Issue by lenciel** [SlEePlEs5/logKext#14]
I've made some modification to make the project build without error. However it failed when packaging the `.pkg` file with error like this:

```
/Developer/Applications/Utilities/PackageMaker.app/Contents/MacOS/PackageMaker: No such file or directory
```

I think PackageMaker is deprecated and could not be used on 10.10?

**Comment by SlEePlEs5** [comment]
Nope, simply that PackageMaker hasn't been included with Xcode since ~mid-2012.

You'll need to go to https://developer.apple.com/downloads/, sign in with your Apple Developer account, and search for and download the package "Auxiliary Tools for Xcode - Late July 2012".

PackageMaker can be found in this package and should be placed in the Applications folder, as suggested by the error message,

**Comment by lenciel** [comment]
thanks for your quick response.
