### ISSUE TITLE
Not running El capitan

### ISSUE THREAD

**Issue by uhlhosting** [SlEePlEs5/logKext#17]
Hello,

I have disabled SIP with SIPutility and I get this after installing the pkg.

  ~  sudo logKextClient
Error: logKext Preferences cannot be found.  Is logKextDaemon running?
➜  ~  ls

**Comment by eklecticgeek** [comment]
Hello, just for info, I just installed logkext in 10.11 and had the same problem, for some reasons I can't actually understand, the daemon is not started by launchd at login anymore. I can't understand why, because when I try running`/Library/Application\ Support/logKext/logKextDaemon` logKext starts and runs with no errors, if I can't find a better way to do this I'm going to run the cmd via a wrapper script, but I'd really love understanding why this happens and eventually fixing it

@highacid I got your same error on first run, but then I tried launching manually and it worked, would you try that too just for being sure we're talking about the same thing? 

any chance that @SlEePlEs5 can provide us with an idea about debugging this issue?

**Comment by eklecticgeek** [comment]
Ok, I got it running, but I don't know exactly how. 2 things that could matter are: 
1) enabled root user
2) re-cheched plist permissions

I tried those 2 things almost sure that wouldn't help, then shut down everything because I had to go away and when I went back at keyboard, the daemon was running normally

I'll try logkext in a different mac in a few days and report
